version: '3'

services:
  linkedin-bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/data
    environment:
      - LINKEDIN_USERNAME=${LINKEDIN_USERNAME}
      - LINKEDIN_PASSWORD=${LINKEDIN_PASSWORD}